version: "3.9"
services:
  # service name
  ctf:
    # specify container name 
    container_name: ctf
    build:
      context: .
    # ports:
    # - "1024:1024"
    entrypoint: "/bin/bash" # entrypoint script
    stdin_open: true # docker run -i
    tty: true # docker run -t
    
    # volume so that we can have the ctf payloads written in our host machine in ./ctf_files folder,
    # and then run the files inside docker for security purpose
    volumes:
      - "./ctf_files:/home/ctf/ctf_files"
